let xT = 5;
let xP = 12;
let proba = 0.15;
let T = new Tresor(xT);
let P = new Personnage(xP);
let C = new Champ(xP,xT,proba);
T.placer();
P.placer();
C.afficher();
// P.mouvement(-1,0);
// P.actualiser_situation(C);